apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: frontend
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/kontejnerizacija-projectnetwork: "true"
        io.kompose.service: frontend
    spec:
      containers:
        - image: localhost:5000/kontejnerizacija-frontend:latest
          name: frontend
          ports:
            - containerPort: 4200
              hostPort: 4200
              protocol: TCP
      restartPolicy: Always
