apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: mongodb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: /snap/kompose/19/kompose-linux-amd64 convert -f docker-compose.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/projectnetwork: "true"
        io.kompose.service: mongodb
    spec:
      containers:
      - image: mongodb
        imagePullPolicy: ""
        name: mongodb
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: app-images-volume
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: app-images-volume
        persistentVolumeClaim:
          claimName: app-images-volume
status: {}
